version: 1.0.{build}

platform:
  - x86
  - x64

configuration:
  - Release

environment:
  PATH: C:\cygwin\bin;C:\Program Files\PowerShell\7;C:\Program Files\PowerShell\7-preview;$(PATH)

init:
  - cmd: echo "Initialization step"

install:
  - ps: |
      if (!(Test-Path "C:\Program Files\PowerShell\7\pwsh.exe")) {
          echo "PowerShell Core not found. Installing PowerShell Core...";
          Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/PowerShell-7.2.0-win-x64.msi -OutFile pwsh.msi;
          Start-Process msiexec.exe -ArgumentList '/i', 'pwsh.msi', '/quiet', '/norestart' -Wait;
          echo "PowerShell Core installed.";
      }
      $env:PATH="C:\Program Files\PowerShell\7;C:\Program Files\PowerShell\7-preview;$env:PATH";
      echo $env:PATH;
  - pwsh -v

build_script:
  - ps: |
      pwsh -Command "Write-Output 'Hello from PowerShell!'"
  - echo "Build script completed"

test_script:
  - ps: |
      pwsh -Command "Write-Output 'Testing PowerShell execution'"
  - echo "Test script completed"
